require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ResearchesController do

  def mock_research(stubs={})
    @mock_research ||= mock_model(Research, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all researches as @researches" do
      Research.stub(:all) { [mock_research] }
      get :index
      assigns(:researches).should eq([mock_research])
    end
  end

  describe "GET show" do
    it "assigns the requested research as @research" do
      Research.stub(:find).with("37") { mock_research }
      get :show, :id => "37"
      assigns(:research).should be(mock_research)
    end
  end

  describe "GET new" do
    it "assigns a new research as @research" do
      Research.stub(:new) { mock_research }
      get :new
      assigns(:research).should be(mock_research)
    end
  end

  describe "GET edit" do
    it "assigns the requested research as @research" do
      Research.stub(:find).with("37") { mock_research }
      get :edit, :id => "37"
      assigns(:research).should be(mock_research)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created research as @research" do
        Research.stub(:new).with({'these' => 'params'}) { mock_research(:save => true) }
        post :create, :research => {'these' => 'params'}
        assigns(:research).should be(mock_research)
      end

      it "redirects to the created research" do
        Research.stub(:new) { mock_research(:save => true) }
        post :create, :research => {}
        response.should redirect_to(research_url(mock_research))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved research as @research" do
        Research.stub(:new).with({'these' => 'params'}) { mock_research(:save => false) }
        post :create, :research => {'these' => 'params'}
        assigns(:research).should be(mock_research)
      end

      it "re-renders the 'new' template" do
        Research.stub(:new) { mock_research(:save => false) }
        post :create, :research => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested research" do
        Research.stub(:find).with("37") { mock_research }
        mock_research.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :research => {'these' => 'params'}
      end

      it "assigns the requested research as @research" do
        Research.stub(:find) { mock_research(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:research).should be(mock_research)
      end

      it "redirects to the research" do
        Research.stub(:find) { mock_research(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(research_url(mock_research))
      end
    end

    describe "with invalid params" do
      it "assigns the research as @research" do
        Research.stub(:find) { mock_research(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:research).should be(mock_research)
      end

      it "re-renders the 'edit' template" do
        Research.stub(:find) { mock_research(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested research" do
      Research.stub(:find).with("37") { mock_research }
      mock_research.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the researches list" do
      Research.stub(:find) { mock_research }
      delete :destroy, :id => "1"
      response.should redirect_to(researches_url)
    end
  end

end
